services:
  mongodb:
    image: mongo:latest
    container_name: crud_tareas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: starlord
      MONGO_INITDB_ROOT_PASSWORD: fedora
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb_data:/data/db
